// OpenSCAD template library for enclosure generation
// Phase 1: Minimal box only

export const MINIMAL_BOX_TEMPLATE = `/**
 * Minimal Box Enclosure Template
 * Generated by OHM - https://github.com/your-repo
 * 
 * Print Settings:
 * - Layer height: 0.2mm
 * - Infill: 20%
 * - Supports: None needed
 * - Material: PLA or PETG
 */

// === PARAMETERS (edit these to customize) ===
$fn = 32;  // Circle resolution (higher = smoother, slower)

// Enclosure settings
wall = 2;           // Wall thickness (mm) - min 2mm for strength
corner_r = 3;       // Corner radius (mm)
lid_overlap = 10;   // How far lid slides onto base (mm)
tolerance = 0.3;    // Gap for friction fit (mm)

// Component clearances
clearance_sides = 5;    // Space around components (mm)
clearance_top = 5;      // Space above tallest component (mm)
clearance_bottom = 2;   // Space below components (mm)

{{COMPONENT_DIMENSIONS}}

// === DERIVED DIMENSIONS (auto-calculated) ===
{{DERIVED_DIMENSIONS}}

// === MODULES ===

module rounded_box(size, r) {
  hull() {
    for (x = [r, size[0]-r])
      for (y = [r, size[1]-r])
        translate([x, y, 0])
          cylinder(h=size[2], r=r);
  }
}

module base() {
  difference() {
    // Outer shell
    rounded_box([external_width, external_length, base_height], corner_r);
    
    // Component cavity
    translate([wall, wall, wall])
      cube([internal_width, internal_length, internal_height + 1]);
    
    {{CUTOUTS}}
  }
  
  {{MOUNTING_POSTS}}
}

module post(height, hole_diameter) {
  difference() {
    cylinder(h=height, d=hole_diameter + 4);
    translate([0, 0, -1]) cylinder(h=height+2, d=hole_diameter);
  }
}

module lid() {
  difference() {
    // Outer shell
    rounded_box([external_width, external_length, lid_height], corner_r);
    
    // Inner recess (slides onto base)
    translate([wall + tolerance, wall + tolerance, wall])
      cube([
        internal_width - 2*tolerance,
        internal_length - 2*tolerance,
        lid_overlap
      ]);
    
    // Hollow out top
    translate([wall*2, wall*2, -1])
      cube([
        external_width - 4*wall,
        external_length - 4*wall,
        wall + 2
      ]);
  }
}

// === PRINT LAYOUT ===
// Both parts arranged for printing

base();
translate([external_width + 10, 0, 0]) lid();
`;

export const ENCLOSURE_TEMPLATES = {
  minimal_box: MINIMAL_BOX_TEMPLATE,
  // Phase 2: wall_mount, desktop, outdoor
};
